/**
 * Per-site blog engine config. Gitignored — keep this private.
 * Generated by the install walkthrough on 2026-05-12.
 */
import type { BlogConfig } from "@/lib/blog-config";

export const blogConfig: BlogConfig = {
  site: {
    url: "https://lamorindapaving.com",
    name: "Lamorinda Pavers",
    brand: {
      full: "Lamorinda Pavers",
      short: "Lamorinda Pavers",
    },
    locale: "en-US",
  },

  voice: {
    audience:
      "East Bay homeowners (Lafayette, Moraga, Orinda, Walnut Creek, Danville, and the broader Contra Costa / Alameda corridor) planning premium outdoor projects: paver driveways, patios, retaining walls, outdoor kitchens, pool decks, fire features. Upscale market — these are homes with budget for craft, and owners who care how their property looks from the street and during entertaining.",
    tone:
      "Warm, design-forward, polished. Second person. Specific over abstract — name patterns (herringbone, running bond), materials (interlocking concrete pavers, natural stone, porcelain), and the lifestyle outcomes (Saturday entertaining, curb appeal, year-round usability). Practical numbers when they help (warranty terms, resealing cadence, install timelines). Not pushy or hard-sell.",
    mustAvoid: [
      "generic contractor language a competitor could write verbatim",
      "fluff adjectives (premier, top-tier, world-class, unmatched)",
      "talking down to the reader",
      "vague phrases like 'we pride ourselves' or 'rest assured'",
    ],
    mustInclude: [
      "second person ('your home', 'your driveway')",
      "specific East Bay neighborhoods or terrain references when relevant (Happy Valley Road in Lafayette, the Orinda hills, Walnut Creek downtown corridor)",
      "real numbers — install timelines, warranty terms, material comparison data",
      "design vocabulary specific to paving and hardscape (patterns, edge restraints, base aggregate, joint sand)",
    ],
    anchorPosts: 2,
  },

  services: [
    { slug: "paver-driveways", name: "Paver Driveways", summary: "Elevate your home's curb appeal with a custom-designed paver driveway built to last." },
    { slug: "retaining-walls", name: "Retaining Walls", summary: "Functional and beautiful retaining walls that transform sloped terrain into usable outdoor space." },
    { slug: "patios", name: "Patios", summary: "Create your perfect outdoor living space with a custom paver patio designed for your lifestyle." },
    { slug: "artificial-turf", name: "Artificial Turf", summary: "Enjoy a lush, green lawn year-round with zero watering, mowing, or maintenance." },
    { slug: "landscape-design", name: "Landscape Design", summary: "Comprehensive landscape design that brings your outdoor vision to life from concept to completion." },
    { slug: "fire-pits-and-fire-features", name: "Fire Pits & Fire Features", summary: "Add warmth and ambiance to your outdoor space with a custom fire pit or fire feature." },
    { slug: "outdoor-kitchens", name: "Outdoor Kitchens", summary: "Take your entertaining to the next level with a fully equipped custom outdoor kitchen." },
    { slug: "pool-decks", name: "Pool Decks", summary: "Transform the area around your pool with slip-resistant, heat-reflective paver decking." },
    { slug: "putting-greens", name: "Putting Greens", summary: "Practice your short game at home with a professionally installed custom putting green." },
    { slug: "water-features", name: "Water Features", summary: "Add the soothing sound of water to your landscape with custom ponds, fountains, and waterfalls." },
    { slug: "arbors", name: "Arbors & Pergolas", summary: "Define your outdoor space with elegant aluminum or fixed arbors and pergola structures." },
  ],

  geography: [
    { slug: "lafayette", name: "Lafayette", region: "Contra Costa County", tier: 1 },
    { slug: "moraga", name: "Moraga", region: "Contra Costa County", tier: 1 },
    { slug: "orinda", name: "Orinda", region: "Contra Costa County", tier: 1 },
    { slug: "walnut-creek", name: "Walnut Creek", region: "Contra Costa County", tier: 1 },
    { slug: "danville", name: "Danville", region: "Contra Costa County", tier: 2 },
    { slug: "san-ramon", name: "San Ramon", region: "Contra Costa County", tier: 2 },
    { slug: "pleasant-hill", name: "Pleasant Hill", region: "Contra Costa County", tier: 2 },
    { slug: "concord", name: "Concord", region: "Contra Costa County", tier: 2 },
    { slug: "dublin", name: "Dublin", region: "Alameda County", tier: 2 },
    { slug: "martinez", name: "Martinez", region: "Contra Costa County", tier: 3 },
    { slug: "berkeley", name: "Berkeley", region: "Alameda County", tier: 3 },
    { slug: "oakland", name: "Oakland", region: "Alameda County", tier: 3 },
  ],

  branding: {
    // Pulled from lamorindapaving's app/globals.css design tokens.
    // Step 4 wires these into CSS custom properties on the blog routes.
    accentColor: "#E8A83E",      // brand-gold — warm, fits the outdoor/lifestyle feel
    primaryDark: "#1A1612",      // warm-gray-900 — their headings/text color
    fontHeading: "serif",
    fontBody: "sans-serif",
  },

  email: {
    resendDomain: "lamorindapaving.com",
    fromAddress: "Lamorinda Pavers Drafts <drafts@lamorindapaving.com>",
    reviewRecipients: [
      "admin@esquair.com",
      "stevebarsanti@icloud.com",   // Steve Barsanti — owner, Lamorinda Pavers
    ],
  },

  seo: {
    internalLinksPerPost: { min: 12, max: 20 },
    exactMatchAnchorMaxPct: 25,
    faqsPerPost: { min: 5, max: 7 },
  },
};
