/**
 * Interactive setup wizard.
 *
 * Prompts for the minimum fields needed to get a working blog config, then
 * writes blog.config.ts. Stops short of touching GitHub secrets or DNS —
 * those still need manual setup, but the wizard prints the exact checklist
 * at the end.
 *
 * Usage: npm run setup
 */
import { existsSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { resolve } from "node:path";

const CONFIG_PATH = resolve(process.cwd(), "blog.config.ts");

async function main() {
  if (existsSync(CONFIG_PATH)) {
    console.log(
      "blog.config.ts already exists. Delete it first if you want to re-run setup.",
    );
    process.exit(0);
  }

  const rl = createInterface({ input, output });
  const ask = async (q: string, fallback?: string): Promise<string> => {
    const suffix = fallback ? ` [${fallback}]` : "";
    const answer = (await rl.question(`${q}${suffix}: `)).trim();
    return answer || fallback || "";
  };

  console.log("\nBlog engine setup\n─────────────────");
  console.log("Answer the prompts to generate blog.config.ts.\n");

  const siteUrl = await ask("Site URL (e.g. https://example.com)");
  if (!siteUrl.startsWith("http")) {
    console.error("Site URL must start with http:// or https://. Aborting.");
    process.exit(1);
  }

  const siteName = await ask("Site name (e.g. 'Example Co')");
  const brandFull = await ask("Full brand name (e.g. 'Example Construction Inc.')", siteName);
  const brandShort = await ask("Short brand name (e.g. 'Example')", siteName.split(" ")[0]);
  const locale = await ask("Locale", "en-US");

  console.log("\nVoice — be specific. Vague answers produce vague blog posts.\n");
  const audience = await ask(
    "Audience (who's reading)",
  );
  const tone = await ask("Tone (3-5 words)");

  console.log("\nServices — what does this business sell? (comma-separated slugs, e.g. 'roofing,decks')");
  const servicesRaw = await ask("Service slugs (or leave blank for none)");
  const serviceSlugs = servicesRaw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  const services: Array<{ slug: string; name: string; summary: string }> = [];
  for (const slug of serviceSlugs) {
    const name = await ask(`  Display name for '${slug}'`, slug.replace(/-/g, " "));
    const summary = await ask(`  One-line summary for '${slug}'`, `${name} service.`);
    services.push({ slug, name, summary });
  }

  console.log("\nBranding");
  const accent = await ask("Accent color (hex)", "#CC0000");
  const dark = await ask("Primary dark color (hex)", "#222222");
  const fontHeading = await ask("Heading font", "Inter");
  const fontBody = await ask("Body font", "Inter");

  console.log("\nEmail (Resend) — needed for review emails");
  const resendDomain = await ask(
    "Resend-verified domain (e.g. example.com)",
    new URL(siteUrl).hostname.replace(/^www\./, ""),
  );
  const fromAddress = await ask(
    "From address",
    `Drafts <drafts@${resendDomain}>`,
  );
  const reviewRecipientsRaw = await ask(
    "Review email recipients (comma-separated)",
  );
  const reviewRecipients = reviewRecipientsRaw
    .split(",")
    .map((e) => e.trim())
    .filter(Boolean);

  rl.close();

  const config = {
    site: {
      url: siteUrl,
      name: siteName,
      brand: { full: brandFull, short: brandShort },
      locale,
    },
    voice: {
      audience,
      tone,
      mustAvoid: [],
      mustInclude: [],
      anchorPosts: 2,
    },
    services,
    branding: {
      accentColor: accent,
      primaryDark: dark,
      fontHeading,
      fontBody,
    },
    email: {
      resendDomain,
      fromAddress,
      reviewRecipients,
    },
    seo: {
      internalLinksPerPost: { min: 12, max: 20 },
      exactMatchAnchorMaxPct: 25,
      faqsPerPost: { min: 5, max: 7 },
    },
  };

  const body = `/**
 * Generated by \`npm run setup\` on ${new Date().toISOString().slice(0, 10)}.
 * Edit freely — re-running setup won't overwrite an existing config.
 */
import type { BlogConfig } from "@/lib/blog-config";

export const blogConfig: BlogConfig = ${JSON.stringify(config, null, 2)};
`;

  writeFileSync(CONFIG_PATH, body);
  console.log(`\n✓ Wrote ${CONFIG_PATH}\n`);

  console.log("Next steps (not automated — do these manually):");
  console.log("");
  console.log("1. Verify Resend domain");
  console.log(`   - Add ${resendDomain} in Resend dashboard`);
  console.log("   - Add DKIM + SPF DNS records at your DNS provider");
  console.log("");
  console.log("2. Set GitHub Actions secrets");
  console.log("   gh secret set ANTHROPIC_API_KEY");
  console.log("   gh secret set OPENAI_API_KEY");
  console.log("   gh secret set RESEND_API_KEY");
  console.log("   gh secret set NETLIFY_BUILD_HOOK_URL");
  console.log("   gh secret set GSC_SERVICE_ACCOUNT_JSON_BASE64   # optional");
  console.log("");
  console.log("3. Author content/style-reference.md");
  console.log("   The voice anchor that locks AI drafts to your brand voice.");
  console.log("");
  console.log("4. Author your first brief in content/post-queue.json,");
  console.log("   then trigger a test draft:");
  console.log("   gh workflow run weekly-draft.yml --ref main");
  console.log("");
}

main().catch((err) => {
  console.error("Setup failed:", err);
  process.exit(1);
});
